// Smart domain → category database.
// Each domain substring is mapped to a category.
// First match wins, so more specific patterns should come first.

const CATEGORY_COLORS = {
  "Email": "blue",
  "Calendar": "cyan",
  "Dev": "grey",
  "Design": "pink",
  "Social": "blue",
  "Video": "red",
  "Docs": "yellow",
  "Chat": "purple",
  "Shopping": "orange",
  "Finance": "green",
  "News": "cyan",
  "AI Tools": "purple",
  "PM": "green",
  "Music": "pink",
  "Analytics": "orange",
  "Sales & CRM": "blue",
  "Learning": "yellow",
  "Hiring": "red",
};

const DOMAIN_MAP = {
  // ── Email ──
  "mail.google.com": "Email",
  "outlook.live.com": "Email",
  "outlook.office.com/mail": "Email",
  "outlook.office365.com": "Email",
  "mail.yahoo.com": "Email",
  "protonmail.com": "Email",
  "proton.me/mail": "Email",
  "fastmail.com": "Email",
  "hey.com": "Email",
  "mail.zoho.com": "Email",
  "superhuman.com": "Email",
  "front.com": "Email",
  "missiveapp.com": "Email",
  "spark.readdle.com": "Email",

  // ── Calendar ──
  "calendar.google.com": "Calendar",
  "outlook.office.com/calendar": "Calendar",
  "calendly.com": "Calendar",
  "cal.com": "Calendar",
  "savvycal.com": "Calendar",
  "doodle.com": "Calendar",
  "reclaim.ai": "Calendar",
  "morgen.so": "Calendar",

  // ── Dev ──
  "github.com": "Dev",
  "gitlab.com": "Dev",
  "bitbucket.org": "Dev",
  "stackoverflow.com": "Dev",
  "stackexchange.com": "Dev",
  "npmjs.com": "Dev",
  "pypi.org": "Dev",
  "crates.io": "Dev",
  "pkg.go.dev": "Dev",
  "hub.docker.com": "Dev",
  "vercel.com": "Dev",
  "netlify.com": "Dev",
  "render.com": "Dev",
  "railway.app": "Dev",
  "fly.io": "Dev",
  "heroku.com": "Dev",
  "supabase.com": "Dev",
  "firebase.google.com": "Dev",
  "console.cloud.google.com": "Dev",
  "aws.amazon.com": "Dev",
  "portal.azure.com": "Dev",
  "codepen.io": "Dev",
  "codesandbox.io": "Dev",
  "replit.com": "Dev",
  "jsfiddle.net": "Dev",
  "developer.mozilla.org": "Dev",
  "devdocs.io": "Dev",
  "bundlephobia.com": "Dev",
  "regex101.com": "Dev",
  "jsonformatter.org": "Dev",
  "diff.io": "Dev",
  "sourcegraph.com": "Dev",
  "gitpod.io": "Dev",
  "codespaces.github.com": "Dev",
  "lovable.dev": "Dev",
  "cursor.com": "Dev",
  "bolt.new": "Dev",
  "v0.dev": "Dev",
  "planetscale.com": "Dev",
  "neon.tech": "Dev",
  "upstash.com": "Dev",
  "cloudflare.com": "Dev",
  "digitalocean.com": "Dev",
  "sentry.io": "Dev",
  "launchdarkly.com": "Dev",
  "app.n8n.cloud": "Dev",
  "make.com": "Dev",
  "zapier.com": "Dev",
  "retool.com": "Dev",
  "appsmith.com": "Dev",

  // ── Design ──
  "figma.com": "Design",
  "canva.com": "Design",
  "dribbble.com": "Design",
  "behance.net": "Design",
  "sketch.com": "Design",
  "miro.com": "Design",
  "whimsical.com": "Design",
  "excalidraw.com": "Design",
  "framer.com": "Design",
  "webflow.com": "Design",
  "spline.design": "Design",
  "coolors.co": "Design",
  "fontawesome.com": "Design",
  "unsplash.com": "Design",
  "pexels.com": "Design",
  "mobbin.com": "Design",
  "screenlane.com": "Design",
  "gamma.app": "Design",

  // ── Social ──
  "twitter.com": "Social",
  "x.com": "Social",
  "linkedin.com": "Social",
  "facebook.com": "Social",
  "instagram.com": "Social",
  "reddit.com": "Social",
  "threads.net": "Social",
  "mastodon.social": "Social",
  "bsky.app": "Social",
  "producthunt.com": "Social",
  "indiehackers.com": "Social",

  // ── Video ──
  "youtube.com": "Video",
  "vimeo.com": "Video",
  "twitch.tv": "Video",
  "tiktok.com": "Video",
  "dailymotion.com": "Video",
  "loom.com": "Video",

  // ── Docs ──
  "docs.google.com": "Docs",
  "drive.google.com": "Docs",
  "notion.so": "Docs",
  "notion.site": "Docs",
  "airtable.com": "Docs",
  "coda.io": "Docs",
  "dropbox.com": "Docs",
  "box.com": "Docs",
  "onedrive.live.com": "Docs",
  "sharepoint.com": "Docs",
  "confluence.atlassian.com": "Docs",
  "gitbook.io": "Docs",
  "slite.com": "Docs",
  "almanac.io": "Docs",
  "craft.do": "Docs",
  "quip.com": "Docs",
  "paper.dropbox.com": "Docs",

  // ── Chat ──
  "app.slack.com": "Chat",
  "slack.com": "Chat",
  "discord.com": "Chat",
  "teams.microsoft.com": "Chat",
  "web.telegram.org": "Chat",
  "web.whatsapp.com": "Chat",
  "messenger.com": "Chat",
  "meet.google.com": "Chat",
  "zoom.us": "Chat",
  "gather.town": "Chat",
  "around.co": "Chat",
  "livekit.io": "Chat",
  "riverside.fm": "Chat",

  // ── Shopping ──
  "amazon.com": "Shopping",
  "ebay.com": "Shopping",
  "walmart.com": "Shopping",
  "target.com": "Shopping",
  "etsy.com": "Shopping",
  "bestbuy.com": "Shopping",
  "newegg.com": "Shopping",
  "aliexpress.com": "Shopping",

  // ── Finance ──
  "chase.com": "Finance",
  "bankofamerica.com": "Finance",
  "wellsfargo.com": "Finance",
  "mint.com": "Finance",
  "venmo.com": "Finance",
  "paypal.com": "Finance",
  "brex.com": "Finance",
  "stripe.com": "Finance",
  "mercury.com": "Finance",
  "wise.com": "Finance",
  "revolut.com": "Finance",
  "plaid.com": "Finance",
  "quickbooks.intuit.com": "Finance",
  "wave.com": "Finance",
  "ramp.com": "Finance",
  "taxact.com": "Finance",
  "turbotax.intuit.com": "Finance",

  // ── News ──
  "news.ycombinator.com": "News",
  "techcrunch.com": "News",
  "theverge.com": "News",
  "arstechnica.com": "News",
  "wired.com": "News",
  "bbc.com": "News",
  "cnn.com": "News",
  "nytimes.com": "News",
  "reuters.com": "News",
  "bloomberg.com": "News",
  "wsj.com": "News",
  "thenextweb.com": "News",
  "engadget.com": "News",
  "9to5mac.com": "News",
  "macrumors.com": "News",
  "substack.com": "News",
  "medium.com": "News",
  "beehiiv.com": "News",

  // ── AI Tools ──
  "chat.openai.com": "AI Tools",
  "chatgpt.com": "AI Tools",
  "claude.ai": "AI Tools",
  "gemini.google.com": "AI Tools",
  "perplexity.ai": "AI Tools",
  "poe.com": "AI Tools",
  "midjourney.com": "AI Tools",
  "huggingface.co": "AI Tools",
  "replicate.com": "AI Tools",
  "together.ai": "AI Tools",
  "groq.com": "AI Tools",
  "openrouter.ai": "AI Tools",
  "stability.ai": "AI Tools",
  "elevenlabs.io": "AI Tools",
  "descript.com": "AI Tools",
  "runway.ml": "AI Tools",
  "jasper.ai": "AI Tools",
  "copy.ai": "AI Tools",
  "writesonic.com": "AI Tools",
  "character.ai": "AI Tools",

  // ── Project Management ──
  "linear.app": "PM",
  "asana.com": "PM",
  "trello.com": "PM",
  "monday.com": "PM",
  "clickup.com": "PM",
  "jira.atlassian.com": "PM",
  "basecamp.com": "PM",
  "height.app": "PM",
  "shortcut.com": "PM",
  "todoist.com": "PM",
  "ticktick.com": "PM",
  "plane.so": "PM",

  // ── Music ──
  "open.spotify.com": "Music",
  "music.apple.com": "Music",
  "soundcloud.com": "Music",
  "music.youtube.com": "Music",
  "tidal.com": "Music",
  "bandcamp.com": "Music",

  // ── Analytics ──
  "analytics.google.com": "Analytics",
  "mixpanel.com": "Analytics",
  "amplitude.com": "Analytics",
  "plausible.io": "Analytics",
  "posthog.com": "Analytics",
  "hotjar.com": "Analytics",
  "clarity.microsoft.com": "Analytics",
  "looker.google.com": "Analytics",
  "datastudio.google.com": "Analytics",
  "semrush.com": "Analytics",
  "ahrefs.com": "Analytics",
  "similarweb.com": "Analytics",

  // ── Sales & CRM ──
  "salesforce.com": "Sales & CRM",
  "hubspot.com": "Sales & CRM",
  "pipedrive.com": "Sales & CRM",
  "close.com": "Sales & CRM",
  "apollo.io": "Sales & CRM",
  "outreach.io": "Sales & CRM",
  "salesloft.com": "Sales & CRM",
  "gong.io": "Sales & CRM",
  "zoominfo.com": "Sales & CRM",
  "lusha.com": "Sales & CRM",
  "clearbit.com": "Sales & CRM",
  "lemlist.com": "Sales & CRM",
  "instantly.ai": "Sales & CRM",
  "clay.com": "Sales & CRM",
  "attio.com": "Sales & CRM",

  // ── Learning ──
  "coursera.org": "Learning",
  "udemy.com": "Learning",
  "edx.org": "Learning",
  "khanacademy.org": "Learning",
  "skillshare.com": "Learning",
  "pluralsight.com": "Learning",
  "egghead.io": "Learning",
  "frontendmasters.com": "Learning",
  "codecademy.com": "Learning",
  "freecodecamp.org": "Learning",
  "leetcode.com": "Learning",
  "exercism.org": "Learning",

  // ── Hiring ──
  "lever.co": "Hiring",
  "greenhouse.io": "Hiring",
  "ashbyhq.com": "Hiring",
  "dover.com": "Hiring",
  "wellfound.com": "Hiring",
  "angel.co": "Hiring",
  "indeed.com": "Hiring",
  "glassdoor.com": "Hiring",
  "linkedin.com/talent": "Hiring",
  "linkedin.com/recruiter": "Hiring",
  "workable.com": "Hiring",
  "breezy.hr": "Hiring",
};

// Export for service worker
if (typeof self !== "undefined") {
  self.CATEGORY_COLORS = CATEGORY_COLORS;
  self.DOMAIN_MAP = DOMAIN_MAP;
}
